/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceIdRouteImport } from './routes/$workspaceId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIdIndexRouteImport } from './routes/$workspaceId/index'
import { Route as WorkspaceIdSettingsRouteImport } from './routes/$workspaceId/settings'
import { Route as WorkspaceIdMissionsRouteImport } from './routes/$workspaceId/missions'
import { Route as WorkspaceIdArtifactsRouteImport } from './routes/$workspaceId/artifacts'
import { Route as WorkspaceIdAgentsRouteImport } from './routes/$workspaceId/agents'
import { Route as WorkspaceIdActivityRouteImport } from './routes/$workspaceId/activity'

const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdIndexRoute = WorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdSettingsRoute = WorkspaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdMissionsRoute = WorkspaceIdMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdArtifactsRoute = WorkspaceIdArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdAgentsRoute = WorkspaceIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdActivityRoute = WorkspaceIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => WorkspaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteWithChildren
  '/$workspaceId/activity': typeof WorkspaceIdActivityRoute
  '/$workspaceId/agents': typeof WorkspaceIdAgentsRoute
  '/$workspaceId/artifacts': typeof WorkspaceIdArtifactsRoute
  '/$workspaceId/missions': typeof WorkspaceIdMissionsRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRoute
  '/$workspaceId/': typeof WorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$workspaceId/activity': typeof WorkspaceIdActivityRoute
  '/$workspaceId/agents': typeof WorkspaceIdAgentsRoute
  '/$workspaceId/artifacts': typeof WorkspaceIdArtifactsRoute
  '/$workspaceId/missions': typeof WorkspaceIdMissionsRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRoute
  '/$workspaceId': typeof WorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteWithChildren
  '/$workspaceId/activity': typeof WorkspaceIdActivityRoute
  '/$workspaceId/agents': typeof WorkspaceIdAgentsRoute
  '/$workspaceId/artifacts': typeof WorkspaceIdArtifactsRoute
  '/$workspaceId/missions': typeof WorkspaceIdMissionsRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRoute
  '/$workspaceId/': typeof WorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceId'
    | '/$workspaceId/activity'
    | '/$workspaceId/agents'
    | '/$workspaceId/artifacts'
    | '/$workspaceId/missions'
    | '/$workspaceId/settings'
    | '/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspaceId/activity'
    | '/$workspaceId/agents'
    | '/$workspaceId/artifacts'
    | '/$workspaceId/missions'
    | '/$workspaceId/settings'
    | '/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/$workspaceId'
    | '/$workspaceId/activity'
    | '/$workspaceId/agents'
    | '/$workspaceId/artifacts'
    | '/$workspaceId/missions'
    | '/$workspaceId/settings'
    | '/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceIdRoute: typeof WorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$workspaceId': {
      id: '/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/': {
      id: '/$workspaceId/'
      path: '/'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof WorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/settings': {
      id: '/$workspaceId/settings'
      path: '/settings'
      fullPath: '/$workspaceId/settings'
      preLoaderRoute: typeof WorkspaceIdSettingsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/missions': {
      id: '/$workspaceId/missions'
      path: '/missions'
      fullPath: '/$workspaceId/missions'
      preLoaderRoute: typeof WorkspaceIdMissionsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/artifacts': {
      id: '/$workspaceId/artifacts'
      path: '/artifacts'
      fullPath: '/$workspaceId/artifacts'
      preLoaderRoute: typeof WorkspaceIdArtifactsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/agents': {
      id: '/$workspaceId/agents'
      path: '/agents'
      fullPath: '/$workspaceId/agents'
      preLoaderRoute: typeof WorkspaceIdAgentsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/activity': {
      id: '/$workspaceId/activity'
      path: '/activity'
      fullPath: '/$workspaceId/activity'
      preLoaderRoute: typeof WorkspaceIdActivityRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
  }
}

interface WorkspaceIdRouteChildren {
  WorkspaceIdActivityRoute: typeof WorkspaceIdActivityRoute
  WorkspaceIdAgentsRoute: typeof WorkspaceIdAgentsRoute
  WorkspaceIdArtifactsRoute: typeof WorkspaceIdArtifactsRoute
  WorkspaceIdMissionsRoute: typeof WorkspaceIdMissionsRoute
  WorkspaceIdSettingsRoute: typeof WorkspaceIdSettingsRoute
  WorkspaceIdIndexRoute: typeof WorkspaceIdIndexRoute
}

const WorkspaceIdRouteChildren: WorkspaceIdRouteChildren = {
  WorkspaceIdActivityRoute: WorkspaceIdActivityRoute,
  WorkspaceIdAgentsRoute: WorkspaceIdAgentsRoute,
  WorkspaceIdArtifactsRoute: WorkspaceIdArtifactsRoute,
  WorkspaceIdMissionsRoute: WorkspaceIdMissionsRoute,
  WorkspaceIdSettingsRoute: WorkspaceIdSettingsRoute,
  WorkspaceIdIndexRoute: WorkspaceIdIndexRoute,
}

const WorkspaceIdRouteWithChildren = WorkspaceIdRoute._addFileChildren(
  WorkspaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceIdRoute: WorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
